[build]
  command = "npm run production"
  publish = "build_production"
  environment = { PHP_VERSION = "7.2" }

[[headers]]
  for = "*.woff"
  [headers.values]
    cache-control = "public, max-age=31536000"

[[headers]]
  for = "*.eof"
  [headers.values]
    cache-control = "public, max-age=31536000"

[[headers]]
  for = "*.ttf"
  [headers.values]
    cache-control = "public, max-age=31536000"

[[headers]]
  for = "*.css"
  [headers.values]
    cache-control = "public, max-age=31536000"

[[headers]]
  for = "*.js"
  [headers.values]
    cache-control = "public, max-age=31536000"
